### ISSUE TITLE
cargo install:   invalid serialized PackageId for key `package.dependencies`

### ISSUE THREAD

**Issue by skybert** [SoptikHa2/desed#14]
```
root@foo ~ # cargo install desed
    Updating crates.io index
  Downloaded desed v1.1.4
  Downloaded 1 crates (1.4 MB) in 2.38s (largest was `desed` at 1.4 MB)
  Installing desed v1.1.4
error: failed to compile `desed v1.1.4`, intermediate artifacts can be found at `/tmp/cargo-install0G6OX1`

Caused by:
  failed to parse lock file at: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/desed-1.1.4/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
```

```
# cargo --version
cargo 1.34.0
```

**Comment by SoptikHa2** [comment]
Huh, that's weird, it works for me just fine. Maybe try to update? I have version `1.43.0`, it's possible that it's using some new feature that yours don't have yet. Maybe it's because of [this](https://github.com/rust-lang/cargo/pull/7579), which would require you to update to at least `1.38.0`.

If you don't want to update you can download prebuilt binary for linux, but that would be painful to update and you would have to trust me that the binary comes from this source code and I didn't add anything extra to it.

**Comment by skybert** [comment]
Upgrading to `1.42.1` (the version in Debian/bullseye) solved the problem.  Thanks for your swift reply.
