### ISSUE TITLE
desed doesn't restore terminal settings

### ISSUE THREAD

**Issue by yurivict** [SoptikHa2/desed#9]
Calling ```desed``` with bad arguments fails to restore the terminal settings:
```
$ desed x.sed input.txt 
sed: illegal option -- -
usage: sed script [-Ealnru] [-i extension] [file ...]
	sed [-Ealnu] [-i extension] [-e script] ... [-f script_file] ... [file ...]
An error occured: It looks like the source code loaded was empty. Nothing to do.
Erase set to backspace.                                                         [yuri@yv /usr/ports/devel/desed]$ [yuri@yv /usr/ports/devel/desed]$ 
```

**Comment by SoptikHa2** [comment]
Status: found cause and have POC solution.

The reason is because we switch terminal to raw mode, but don't switch it back. This for some reason propagates to main screen even if alternate screen is used for everything else. I thought that using alternate screen will take care of it for us.

This means that we have to unset raw mode manually, which is not really nice and I don't like it, since if we want to do it in every case, then due to the way error handling works, I'll have to put it in main. I don't like putting TUI things in main. Also we will leave terminal in broken state if we ever panic with no way to handle it.

I have a fix ready locally. I'll figure the best way to apply it and release new fixed version tomorrow.
